# Generated by Django 6.0.1 on 2026-02-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='electronics/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.brand')),
            ],
        ),
    ]
